### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Danskii** [DaddyWarbucks/static-google-map#4]
I'm trying to generate a Google static map image URL with this package: [static-google-map][1].

I get the following error after trying to run: 

```
import { staticMapUrl } from 'static-google-map';
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
```

Here is my code. I have excluded the API key.

```
const realtor = require("realtorca");
const unirest = require("unirest");
const nodemailer = require("nodemailer");
import { staticMapUrl } from 'static-google-map';
 
const url = staticMapUrl({
  key: 'YOUR_API_KEY',
  scale: 1,
  size: '600x600',
  format: 'png',
  maptype: 'roadmap'
});
 
console.log(url);
```

  [1]: https://www.npmjs.com/package/static-google-map

**Comment by DaddyWarbucks** [comment]
You need to use `require` in node. Node does not support ES6 modules.

Try `const  { staticMapUrl } = require('static-google-map')`

**Comment by DaddyWarbucks** [comment]
@Danskii I am going to go ahead and close this because I don't believe it is a bug. Let me know if you have any more questions or if the above does not work. Thanks!
